"""
Sample data for populating the knitting knowledge base.

This module contains initial patterns and yarns to demonstrate
the RAG architecture capabilities.
"""

from .schemas import DifficultyLevel, StitchPattern, YarnInfo, YarnWeight

# Sample stitch patterns migrated from existing hardcoded patterns
SAMPLE_PATTERNS = [
    StitchPattern(
        id="stockinette",
        name="Stockinette Stitch",
        category="basic",
        difficulty=DifficultyLevel.BEGINNER,
        repeat_width=1,
        repeat_height=2,
        instructions=[
            "Row 1 (RS): Knit all stitches",
            "Row 2 (WS): Purl all stitches",
            "Repeat rows 1-2",
        ],
        gauge_modifier=1.0,
        recommended_yarn_weights=[
            YarnWeight.FINGERING,
            YarnWeight.SPORT,
            YarnWeight.DK,
            YarnWeight.WORSTED,
        ],
        lies_flat=False,
        has_curl=True,
        stretch_horizontal=1.1,
        stretch_vertical=1.2,
        best_for=["sweaters", "blankets", "accessories"],
        combines_well_with=["seed_stitch", "garter_stitch", "ribbing"],
        stitch_count_multiple=1,
        edge_stitches_needed=0,
        requires_border=True,
        description="The most common knitting stitch, creating a smooth fabric with natural curl.",
        tips=[
            "Maintain consistent tension for even fabric",
            "Use a border pattern to prevent curling",
            "Great for colorwork and texture combinations",
        ],
        common_mistakes=[
            "Inconsistent tension causing uneven stitches",
            "Forgetting to alternate knit and purl rows",
            "Not accounting for natural curl in finished measurements",
        ],
        variations=["Reverse stockinette", "Broken stockinette"],
        keywords=["basic", "smooth", "curl", "knit", "purl", "fundamental"],
    ),
    StitchPattern(
        id="seed_stitch",
        name="Seed Stitch",
        category="textured",
        difficulty=DifficultyLevel.EASY,
        repeat_width=2,
        repeat_height=2,
        instructions=[
            "Row 1: *K1, P1; repeat from * to end",
            "Row 2: *P1, K1; repeat from * to end",
            "Repeat rows 1-2",
        ],
        gauge_modifier=0.9,
        recommended_yarn_weights=[
            YarnWeight.SPORT,
            YarnWeight.DK,
            YarnWeight.WORSTED,
            YarnWeight.BULKY,
        ],
        lies_flat=True,
        has_curl=False,
        stretch_horizontal=0.9,
        stretch_vertical=0.95,
        best_for=["borders", "blankets", "scarves", "dishcloths"],
        combines_well_with=["stockinette", "garter_stitch", "cables"],
        stitch_count_multiple=2,
        edge_stitches_needed=0,
        requires_border=False,
        description="Creates a textured, non-curling fabric perfect for borders and blankets.",
        tips=[
            "Keep track of odd vs even rows to maintain pattern",
            "Use stitch markers for pattern repeats",
            "Excellent for beginner texture practice",
        ],
        common_mistakes=[
            "Losing track of knit/purl sequence",
            "Inconsistent stitch size",
            "Not maintaining pattern at edges",
        ],
        variations=["Moss stitch", "Double seed stitch"],
        keywords=[
            "textured",
            "border",
            "non-curling",
            "alternating",
            "bumpy",
            "stable",
        ],
    ),
    StitchPattern(
        id="simple_cable",
        name="Simple Cable",
        category="cable",
        difficulty=DifficultyLevel.INTERMEDIATE,
        repeat_width=8,
        repeat_height=8,
        instructions=[
            "Row 1 (RS): P2, K4, P2",
            "Row 2 (WS): K2, P4, K2",
            "Row 3: P2, K4, P2",
            "Row 4: K2, P4, K2",
            "Row 5: P2, slip 2 sts to cable needle and hold in front, K2, K2 from cable needle, P2",
            "Row 6: K2, P4, K2",
            "Row 7: P2, K4, P2",
            "Row 8: K2, P4, K2",
        ],
        gauge_modifier=0.85,
        recommended_yarn_weights=[YarnWeight.DK, YarnWeight.WORSTED, YarnWeight.BULKY],
        lies_flat=True,
        has_curl=False,
        stretch_horizontal=0.8,
        stretch_vertical=0.9,
        best_for=["sweaters", "blankets", "accessories"],
        combines_well_with=["stockinette", "seed_stitch", "ribbing"],
        stitch_count_multiple=8,
        edge_stitches_needed=2,
        requires_border=False,
        description="A basic cable pattern that creates twisted rope-like columns.",
        tips=[
            "Use a cable needle or learn to cable without one",
            "Keep cable stitches snug but not tight",
            "Count rows carefully to maintain cable crossing rhythm",
        ],
        common_mistakes=[
            "Crossing cables in wrong direction",
            "Forgetting to cross cables on the designated row",
            "Making cable stitches too tight",
        ],
        variations=["Left-leaning cable", "Wide cable", "Honeycomb cable"],
        keywords=["cable", "twisted", "rope", "textured", "dimensional", "crossing"],
    ),
    StitchPattern(
        id="garter_stitch",
        name="Garter Stitch",
        category="basic",
        difficulty=DifficultyLevel.BEGINNER,
        repeat_width=1,
        repeat_height=1,
        instructions=["All rows: Knit all stitches"],
        gauge_modifier=0.8,
        recommended_yarn_weights=[
            YarnWeight.FINGERING,
            YarnWeight.SPORT,
            YarnWeight.DK,
            YarnWeight.WORSTED,
            YarnWeight.BULKY,
        ],
        lies_flat=True,
        has_curl=False,
        stretch_horizontal=1.0,
        stretch_vertical=1.4,
        best_for=["blankets", "scarves", "dishcloths", "borders"],
        combines_well_with=["stockinette", "seed_stitch", "ribbing"],
        stitch_count_multiple=1,
        edge_stitches_needed=0,
        requires_border=False,
        description="The simplest knitting stitch, created by knitting every row.",
        tips=[
            "Perfect for beginners",
            "Creates a squishy, non-curling fabric",
            "Great for combining with other patterns",
        ],
        common_mistakes=[
            "Accidentally purling instead of knitting",
            "Inconsistent edge stitches",
        ],
        variations=["Broken garter", "Garter ridges"],
        keywords=["basic", "simple", "beginner", "squishy", "non-curling", "ridged"],
    ),
    StitchPattern(
        id="ribbing_2x2",
        name="2x2 Ribbing",
        category="ribbing",
        difficulty=DifficultyLevel.EASY,
        repeat_width=4,
        repeat_height=1,
        instructions=["All rows: *K2, P2; repeat from * to end"],
        gauge_modifier=0.7,
        recommended_yarn_weights=[YarnWeight.SPORT, YarnWeight.DK, YarnWeight.WORSTED],
        lies_flat=True,
        has_curl=False,
        stretch_horizontal=0.6,
        stretch_vertical=1.0,
        best_for=["sweater_cuffs", "hat_brims", "fitted_garments"],
        combines_well_with=["stockinette", "cables"],
        stitch_count_multiple=4,
        edge_stitches_needed=0,
        requires_border=False,
        description="A stretchy ribbing pattern perfect for garment edges.",
        tips=[
            "Maintain consistent tension for even ribs",
            "Use smaller needles for tighter ribbing",
            "Great for creating fitted sections",
        ],
        common_mistakes=[
            "Losing track of knit/purl sequence",
            "Making ribbing too loose",
            "Not maintaining pattern consistency",
        ],
        variations=["1x1 ribbing", "3x3 ribbing", "Twisted ribbing"],
        keywords=["ribbing", "stretchy", "fitted", "elastic", "cuffs", "edges"],
    ),
    # Additional patterns to expand the database
    StitchPattern(
        id="moss_stitch",
        name="Moss Stitch",
        category="textured",
        difficulty=DifficultyLevel.EASY,
        repeat_width=2,
        repeat_height=4,
        instructions=[
            "Row 1: *K1, P1; repeat from * to end",
            "Row 2: *K1, P1; repeat from * to end",
            "Row 3: *P1, K1; repeat from * to end",
            "Row 4: *P1, K1; repeat from * to end",
        ],
        gauge_modifier=0.85,
        recommended_yarn_weights=[YarnWeight.SPORT, YarnWeight.DK, YarnWeight.WORSTED],
        lies_flat=True,
        has_curl=False,
        stretch_horizontal=0.85,
        stretch_vertical=0.9,
        best_for=["blankets", "scarves", "textured_sections"],
        combines_well_with=["stockinette", "cables", "seed_stitch"],
        stitch_count_multiple=2,
        edge_stitches_needed=0,
        requires_border=False,
        description="A variation of seed stitch with a different texture pattern.",
        tips=[
            "More structured than seed stitch",
            "Creates interesting texture combinations",
            "Good for accent panels",
        ],
        common_mistakes=[
            "Confusing with seed stitch pattern",
            "Inconsistent row tracking",
        ],
        variations=["Irish moss stitch", "Double moss stitch"],
        keywords=["textured", "moss", "alternating", "structured", "accent"],
    ),
    StitchPattern(
        id="basketweave",
        name="Basketweave Stitch",
        category="textured",
        difficulty=DifficultyLevel.INTERMEDIATE,
        repeat_width=8,
        repeat_height=8,
        instructions=[
            "Row 1: *K4, P4; repeat from * to end",
            "Row 2: *K4, P4; repeat from * to end",
            "Row 3: *K4, P4; repeat from * to end",
            "Row 4: *K4, P4; repeat from * to end",
            "Row 5: *P4, K4; repeat from * to end",
            "Row 6: *P4, K4; repeat from * to end",
            "Row 7: *P4, K4; repeat from * to end",
            "Row 8: *P4, K4; repeat from * to end",
        ],
        gauge_modifier=0.9,
        recommended_yarn_weights=[YarnWeight.DK, YarnWeight.WORSTED, YarnWeight.BULKY],
        lies_flat=True,
        has_curl=False,
        stretch_horizontal=0.9,
        stretch_vertical=0.95,
        best_for=["blankets", "dishcloths", "textured_panels"],
        combines_well_with=["stockinette", "ribbing", "borders"],
        stitch_count_multiple=8,
        edge_stitches_needed=0,
        requires_border=False,
        description="Creates a woven basket-like texture with alternating blocks.",
        tips=[
            "Keep track of 4-row blocks",
            "Use stitch markers for pattern repeats",
            "Great for showing off variegated yarns",
        ],
        common_mistakes=[
            "Losing track of block changes",
            "Inconsistent tension between knit and purl sections",
        ],
        variations=["Small basketweave", "Large basketweave"],
        keywords=["textured", "blocks", "basketweave", "geometric", "structured"],
    ),
]


# Sample yarns
SAMPLE_YARNS = [
    YarnInfo(
        id="cascade_220",
        name="220 Superwash",
        brand="Cascade Yarns",
        weight=YarnWeight.WORSTED,
        fiber_content={"wool": 1.0},
        fiber_type="natural",
        yardage_per_unit=220,
        unit_weight_grams=100,
        recommended_needle_size="US 7",
        standard_gauge_stitches=18,
        standard_gauge_rows=24,
        gauge_needle_size="US 7",
        care_instructions=["Machine wash cold", "Tumble dry low"],
        machine_washable=True,
        superwash=True,
        ease_of_working=DifficultyLevel.EASY,
        drape="medium",
        warmth="warm",
        durability="durable",
        price_range="budget",
        availability="common",
        colors_available=["natural", "black", "red", "blue", "green", "purple"],
        best_for_patterns=["basic", "cable", "colorwork"],
        not_recommended_for=["lace"],
        keywords=[
            "wool",
            "superwash",
            "machine_washable",
            "durable",
            "budget",
            "worsted",
        ],
    ),
    YarnInfo(
        id="berroco_vintage",
        name="Vintage",
        brand="Berroco",
        weight=YarnWeight.WORSTED,
        fiber_content={"acrylic": 0.52, "wool": 0.40, "nylon": 0.08},
        fiber_type="blend",
        yardage_per_unit=217,
        unit_weight_grams=100,
        recommended_needle_size="US 7",
        standard_gauge_stitches=18,
        standard_gauge_rows=24,
        gauge_needle_size="US 7",
        care_instructions=["Machine wash cold", "Tumble dry low"],
        machine_washable=True,
        superwash=False,
        ease_of_working=DifficultyLevel.EASY,
        drape="medium",
        warmth="medium",
        durability="very_durable",
        price_range="medium",
        availability="common",
        colors_available=["cream", "charcoal", "teal", "burgundy", "navy"],
        best_for_patterns=["basic", "textured", "cable"],
        not_recommended_for=["delicate_lace"],
        keywords=["blend", "acrylic", "wool", "machine_washable", "durable", "vintage"],
    ),
    YarnInfo(
        id="malabrigo_worsted",
        name="Worsted",
        brand="Malabrigo",
        weight=YarnWeight.WORSTED,
        fiber_content={"wool": 1.0},
        fiber_type="natural",
        yardage_per_unit=210,
        unit_weight_grams=100,
        recommended_needle_size="US 7",
        standard_gauge_stitches=18,
        standard_gauge_rows=24,
        gauge_needle_size="US 7",
        care_instructions=["Hand wash cold", "Lay flat to dry"],
        machine_washable=False,
        superwash=False,
        ease_of_working=DifficultyLevel.INTERMEDIATE,
        drape="drapey",
        warmth="very_warm",
        durability="medium",
        price_range="premium",
        availability="common",
        colors_available=["natural", "variegated", "semi_solid", "kettle_dyed"],
        best_for_patterns=["basic", "textured", "cable", "colorwork"],
        not_recommended_for=["structured_garments"],
        keywords=["wool", "hand_dyed", "soft", "premium", "drapey", "warm"],
    ),
    YarnInfo(
        id="lion_brand_wool_ease",
        name="Wool-Ease",
        brand="Lion Brand",
        weight=YarnWeight.WORSTED,
        fiber_content={"acrylic": 0.80, "wool": 0.20},
        fiber_type="blend",
        yardage_per_unit=197,
        unit_weight_grams=85,
        recommended_needle_size="US 8",
        standard_gauge_stitches=16,
        standard_gauge_rows=22,
        gauge_needle_size="US 8",
        care_instructions=["Machine wash warm", "Tumble dry low"],
        machine_washable=True,
        superwash=False,
        ease_of_working=DifficultyLevel.BEGINNER,
        drape="medium",
        warmth="medium",
        durability="durable",
        price_range="budget",
        availability="common",
        colors_available=["basic", "heather", "tweed"],
        best_for_patterns=["basic", "beginner_projects"],
        not_recommended_for=["fine_gauge", "lace"],
        keywords=["acrylic", "wool", "budget", "beginner", "machine_washable", "easy"],
    ),
    # Add some sport weight yarns
    YarnInfo(
        id="cascade_220_sport",
        name="220 Superwash Sport",
        brand="Cascade Yarns",
        weight=YarnWeight.SPORT,
        fiber_content={"wool": 1.0},
        fiber_type="natural",
        yardage_per_unit=164,
        unit_weight_grams=50,
        recommended_needle_size="US 6",
        standard_gauge_stitches=24,
        standard_gauge_rows=32,
        gauge_needle_size="US 6",
        care_instructions=["Machine wash cold", "Tumble dry low"],
        machine_washable=True,
        superwash=True,
        ease_of_working=DifficultyLevel.EASY,
        drape="good",
        warmth="warm",
        durability="durable",
        price_range="budget",
        availability="common",
        colors_available=["natural", "black", "red", "blue", "green", "purple"],
        best_for_patterns=["basic", "textured", "lace"],
        not_recommended_for=["chunky_cables"],
        keywords=["wool", "superwash", "sport", "machine_washable", "fine"],
    ),
    # Add a DK weight yarn
    YarnInfo(
        id="rowan_pure_wool_dk",
        name="Pure Wool DK",
        brand="Rowan",
        weight=YarnWeight.DK,
        fiber_content={"wool": 1.0},
        fiber_type="natural",
        yardage_per_unit=142,
        unit_weight_grams=50,
        recommended_needle_size="US 6",
        standard_gauge_stitches=22,
        standard_gauge_rows=30,
        gauge_needle_size="US 6",
        care_instructions=["Hand wash cold", "Lay flat to dry"],
        machine_washable=False,
        superwash=False,
        ease_of_working=DifficultyLevel.INTERMEDIATE,
        drape="medium",
        warmth="warm",
        durability="durable",
        price_range="premium",
        availability="common",
        colors_available=["natural", "heather", "solid"],
        best_for_patterns=["basic", "cable", "textured", "lace"],
        not_recommended_for=["beginner_projects"],
        keywords=["wool", "dk", "premium", "classic", "british"],
    ),
]


def populate_sample_data(db):
    """Populate database with sample data"""
    print("Adding sample stitch patterns...")
    for pattern in SAMPLE_PATTERNS:
        db.add_stitch_pattern(pattern)

    print("Adding sample yarns...")
    for yarn in SAMPLE_YARNS:
        db.add_yarn(yarn)

    print("Sample data populated successfully!")


if __name__ == "__main__":
    # Quick test of sample data
    from .database import KnowledgeBaseDB

    with KnowledgeBaseDB("test_kb.db") as db:
        populate_sample_data(db)

        # Test queries
        print("\nTesting pattern search...")
        basic_patterns = db.search_stitch_patterns(category="basic")
        print(f"Found {len(basic_patterns)} basic patterns")

        print("\nTesting yarn search...")
        worsted_yarns = db.search_yarns(weight=YarnWeight.WORSTED)
        print(f"Found {len(worsted_yarns)} worsted weight yarns")

        print("\nDatabase populated successfully!")
